[keyboard]
name = "piantor-rmk"
product_name = "piantor-rmk"
vendor_id = 0xbeeb
product_id = 0x0002
manufacturer = "beekeeb"
chip = "rp2040"

[layout]
rows = 4
cols = 10
layers = 4
keymap = [
    [
        ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
        ["MT(A, LCtrl)", "MT(S, LAlt)", "MT(D, LShift)", "MT(F, LGui)", "G", "H", "MT(J, LGui)", "MT(K, LShift)", "MT(L, LAlt)", "MT(Semicolon, LCtrl)"],
        ["Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash"],
        ["No", "No", "_", "Space", "MO(1)", "MO(2)", "MO(3)", "_", "No", "No"]
    ],
    [
        ["WM(1, LShift)", "WM(2, LShift)", "WM(3, LShift)", "WM(4, LShift)", "WM(5, LShift)", "_", "_", "_", "_", "_"],
        ["1", "2", "3", "4", "5", "_", "_", "_", "_", "_"],
        ["F1", "F2", "F3", "F4", "F5", "_", "_", "_", "_", "_"],
        ["No", "No", "_", "_", "_", "_", "_", "_", "No", "No"]
    ],
    [
        ["_", "_", "_", "_", "_", "WM(6, LShift)", "WM(7, LShift)", "WM(8, LShift)", "WM(9, LShift)", "WM(0, LShift)"],
        ["_", "_", "_", "_", "_", "6", "7", "8", "9", "0"],
        ["_", "_", "_", "_", "_", "F6", "F7", "F8", "F9", "F10"],
        ["No", "No", "_", "_", "_", "_", "_", "_", "No", "No"]
    ],
    [
        ["MediaPrevTrack", "MediaPlayPause", "MediaNextTrack", "AudioVolDown", "AudioVolUp", "Escape", "CapsLock", "PageUp", "Backspace", "Delete"],
        ["_", "_", "_", "_", "_", "Left", "Down", "Up", "Right", "Enter"],
        ["Bootloader", "_", "_", "BrightnessDown", "BrightnessUp", "Home", "Tab", "PageDown", "End", "_"],
        ["No", "No", "_", "_", "_", "_", "_", "_", "No", "No"]
    ],
    # [
    #     ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    #     ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    #     ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_"],
    #     ["No", "No", "_", "_", "_", "_", "_", "_", "No", "No"]
    # ],
]

[behavior]
tap_hold = { enable_hrm = true, prior_idle_time = "120ms", hold_timeout = "250ms", post_wait_time = "50ms", permissive_hold = true, chordal_hold = true}

[storage]
enabled = false

[dependency]
defmt_log = false

[rmk]
debounce_time = 60

[split]
connection = "serial"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
serial = [{ instance = "PIO0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]
[split.central.matrix]
matrix_type = "normal"
input_pins = ["PIN_7", "PIN_8", "PIN_9", "PIN_10"]
output_pins = ["PIN_12", "PIN_13", "PIN_14", "PIN_15", "PIN_16"]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5
serial = [{ instance = "PIO0", tx_pin = "PIN_1", rx_pin = "PIN_0" }]
[split.peripheral.matrix]
matrix_type = "normal"
input_pins = ["PIN_7", "PIN_8", "PIN_9", "PIN_10"]
output_pins = ["PIN_16", "PIN_15", "PIN_14", "PIN_13", "PIN_12"]
