[keyboard]
name = "piantor-rmk"
product_name = "piantor-rmk"
vendor_id = 0xbeeb
product_id = 0x0002
manufacturer = "beekeeb"
chip = "rp2040"

[layout]
rows = 4
cols = 10
layers = 3
keymap = [
    [
        ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
        ["MT(A, LCtrl)", "MT(S, LAlt)", "MT(D, LShift)", "MT(F, LGui)", "G", "H", "MT(J, LGui)", "MT(K, LShift)", "MT(L, LAlt)", "MT(Semicolon, LCtrl)"],
        ["Z", "X", "C", "V", "B", "N", "M", "Comma", "Dot", "Slash"],
        ["No", "No", "No", "Space", "MO(1)", "MO(1)", "MO(2)", "No", "No", "No"]
    ],
    [
        ["WM(1, LShift)", "WM(2, LShift)", "WM(3, LShift)", "WM(4, LShift)", "WM(5, LShift)", "WM(6, LShift)", "WM(7, LShift)", "WM(8, LShift)", "WM(9, LShift)", "WM(0, LShift)"],
        ["MT(1, LCtrl)", "MT(2, LAlt)", "MT(3, LShift)", "MT(4, LGui)", "5", "6", "MT(7, LGui)", "MT(8, LShift)", "MT(9, LAlt)", "MT(0, LCtrl)"],
        ["F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10"],
        ["No", "No", "No", "No", "_", "F11", "F12", "No", "No", "No"]
    ],
    [
        ["MediaPrevTrack", "MediaPlayPause", "MediaNextTrack", "AudioVolDown", "AudioVolUp", "Escape", "CapsLock", "PageUp", "Backspace", "Delete"],
        ["LCtrl", "LAlt", "LShift", "LGui", "No", "Left", "Down", "Up", "Right", "Enter"],
        ["No", "No", "No", "BrightnessDown", "BrightnessUp", "Home", "Tab", "PageDown", "End", "No"],
        ["No", "No", "Bootloader", "No", "No", "No", "_", "No", "No", "No"]
    ],
    # [
    #     ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
    #     ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
    #     ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No"],
    #     ["No", "No", "No", "No", "No", "No", "No", "No", "No", "No"]
    # ],
]

[behavior.combo]
timeout = "150ms"
combos = [
  { actions = ["E", "R"], output = "-" },
  { actions = ["R", "T"], output = "=" },
]


[behavior]
tap_hold = { enable_hrm = true, prior_idle_time = "80ms", hold_timeout = "200ms", post_wait_time = "0ms", permissive_hold = true, chordal_hold = true}

[storage]
enabled = false

[dependency]
defmt_log = false

[split]
connection = "serial"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
serial = [{ instance = "PIO0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]
[split.central.matrix]
matrix_type = "normal"
input_pins = ["PIN_7", "PIN_8", "PIN_9", "PIN_10"]
output_pins = ["PIN_12", "PIN_13", "PIN_14", "PIN_15", "PIN_16"]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 5
serial = [{ instance = "PIO0", tx_pin = "PIN_1", rx_pin = "PIN_0" }]
[split.peripheral.matrix]
matrix_type = "normal"
input_pins = ["PIN_7", "PIN_8", "PIN_9", "PIN_10"]
output_pins = ["PIN_16", "PIN_15", "PIN_14", "PIN_13", "PIN_12"]
