[keyboard]
name = "piantor-rmk"
product_name = "piantor-rmk"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "RMK"
chip = "rp2040"

[layout]
rows = 4
cols = 10
layers = 1
keymap = [
    [
        ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
        ["A", "S", "D", "F", "G", "H", "J", "K", "L", "-"],
        ["Z", "X", "C", "V", "B", "N", "M", "-", "-", "-"],
        ["-", "-", "-", "Space", "-", "-", "-", "-", "-", "-"]
    ],
]

[storage]
clear_storage = true

[split]
connection = "serial"

[split.central]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
serial = [
    { instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" },
]
[split.central.matrix]
matrix_type = "normal"
input_pins = ["PIN_7", "PIN_8", "PIN_9", "PIN_10"]
output_pins = ["PIN_12", "PIN_13", "PIN_14", "PIN_15", "PIN_16"]

[[split.peripheral]]
rows = 4
cols = 5
row_offset = 0
col_offset = 0
serial = [{ instance = "UART0", tx_pin = "PIN_0", rx_pin = "PIN_1" }]
[split.peripheral.matrix]
matrix_type = "normal"
input_pins = ["PIN_7", "PIN_8", "PIN_9", "PIN_10"]
output_pins = ["PIN_12", "PIN_13", "PIN_14", "PIN_15", "PIN_16"]
